version: "3.3"
services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: example_db
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: python config/manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - "postgresdb"
